package com.myapp.mysimon.model

/**
 * Class managing the core mathematical logic of the Simon game.
 * An instance of this class tracks the current sequence generated by the app,
 * its length, and maps button indices to their string representations.
 */
class SimonGame {
    // Alphanumeric shorthand letters representing the 6 game colors: Red, Magenta, Green, Yellow, Blue, Cyan
    private val colorsLetters = listOf("R", "M", "G", "Y", "B", "C")

    // List containing integers between 0 and 5, where each integer represents a specific color button
    val sequence: MutableList<Int> = mutableListOf()

    // Total count or length of the current color sequence
    var count: Int = 0

    /**
     * Appends a new color index to the sequence and updates the turn counter.
     * @param btn The integer index (0-5) representing the next button in the sequence.
     */
    fun increment(btn: Int) {
        sequence.add(btn)
        count++
    }

    /**
     * Converts the sequence integers into a single readable, comma-separated string of characters.
     * Optionally limits the generation up to a specific index to show user progress.
     * 
     * @param index The exclusive end boundary for printing the sequence (defaults to full length).
     * @return A comma-separated string representation of the sequence steps (e.g., "R, G, B").
     */
    fun getSequenceString(index: Int = count) : String {
        var s = ""
        // If the sequence is empty or the index boundary is invalid, return an empty string
        if (sequence.isEmpty() || index <= 0) {
            return s
        }
        
        // Initialize the string with the first color character
        s = colorsLetters[sequence[0]]
        // Loop through the rest of the sequence elements up to the requested index boundary
        for (i in 1 until index) {
            s += ", " + colorsLetters[sequence[i]]
        }
        return s
    }

    /**
     * Clears all elements from the current sequence and resets the counter to zero.
     * Prepares the object structure for a completely new game session.
     */
    fun reset() {
        sequence.clear()
        count = 0
    }
}
